#
# Defaults
#
defaults: &defaults
  #encoding: utf8
  reconnect: true
  adapter: mysql2
  pool: 25
  strict: false

#
# Development
#
development: &development
  <<: *defaults
  host: localhost
  database: think
  username: root
  password:
  
#
# Test
#
test: &test
  <<: *defaults
  host: localhost
  database: think_test
  username: root
  password:
